### ISSUE TITLE
password-secret parameter not implemented

### ISSUE THREAD

**Issue by yhaenggi** [rajch/weave-endpoint#2]
The documentation refers to setting the WEAVE_PASSWORD env via password-secret GET parameter.
YAMLs returned by the service dont contain the env with the secretref.

it should have a block like this:
```
        - name: WEAVE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: weave-passwd
              name: weave-passwd
```
